version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world-ts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wmuaxcbxzg0j"
s3_prefix = "sam-hello-world-ts"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
